<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />
    <xacro:property name="arm_radius" value="0.02" />
    <xacro:property name="arm_length" value="0.3" />



    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${arm_base_height / 2.0}" rpy="0.0 0.0 0.0"/>
            <material name ="orange" />
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0.0 0.0 ${arm_base_height / 2.0}" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:box_inertia m="0.5" l="${arm_base_length}" w="${arm_base_width}" h="${arm_base_height}"
                            xyz="0.0 0.0 ${arm_base_height / 2.0}" rpy="0.0 0.0 0.0" />
    </link>


    <xacro:macro name="arm_link" params="prefix_name prefix_material">
        <link name="${prefix_name}">
            <visual>
                <geometry>
                    <cylinder radius="${arm_radius}" length="${arm_length}" />
                </geometry>
                <origin xyz="0 0 ${arm_length / 2.0}" rpy="0 0 0" />
                <material name="${prefix_material}" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${arm_radius}" length="${arm_length}" />
                </geometry>
                <origin xyz="0 0 ${arm_length / 2.0}" rpy="0 0 0" />
            </collision>
            <xacro:cylinder_intertia m="0.3" r="${arm_radius}" h="${arm_length}"
                            xyz="0.0 0.0 ${arm_length / 2.0}"  rpy="0.0 0.0 0.0" /> 
        </link>
    </xacro:macro>

    <xacro:arm_link prefix_name="forearm_link" prefix_material="yellow" />
    <xacro:arm_link prefix_name="hand_link" prefix_material="orange" />



    <joint name="base_arm_base_joint" type="fixed" >
        <parent link="base_link" />
        <child link="arm_base_link" />
        <origin xyz="${base_length / 3.0} 0 ${base_height}" rpy="0 0 0" />
    </joint>

    <joint name="arm_base_forearm_joint" type="revolute">
        <origin xyz="0.0 0.0 ${arm_base_height}" rpy="0.0 0.0 0.0"/>
        <parent link="arm_base_link"/>
        <child link="forearm_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="0.0" upper="1.57" effort="100.0" velocity="100.0"/>
        <dynamics friction="0.05" damping="0.1" />
    </joint>

    <joint name="forearm_hand_joint" type="revolute">
        <origin xyz="0.0 0.0 ${arm_length}" rpy="0.0 0.0 0.0"/>
        <parent link="forearm_link"/>
        <child link="hand_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="0.0" upper="1.57" effort="100.0" velocity="100.0"/>
        <dynamics friction="0.05" damping="0.1" />
    </joint>
    


</robot>